-- Skema basis data ground truth SPKU (DLH DKI Jakarta) pada PostgreSQL 16 + PostGIS.
--
-- Porting dari skema SQLite kolektor udara-collector. Mengikuti konvensi
-- Dokumen Desain (Tugas 3) subbab 3.5: satu instance PostgreSQL, satu skema
-- per basis data logis. Skema ini berdampingan dengan skema `pollution`
-- (Spatial Pollution Cache DB) dan `osm` (OSM Cache DB).
--
-- Nama skema tidak ditulis di sini. Store menetapkan search_path ke
-- "<skema>, public" sebelum menjalankan berkas ini, sehingga skema yang sama
-- dapat dipakai ulang untuk pengujian terisolasi.
--
-- Prinsip yang dipertahankan dari versi SQLite: observasi bersifat menetap.
-- Satu baris ditentukan oleh (stasiun, parameter, cap waktu). Bila portal
-- kelak mengubah nilai pada koordinat yang sama, nilai lama TIDAK ditimpa
-- diam-diam melainkan dicatat pada observation_revision.
--
-- Perubahan tipe terhadap versi SQLite:
--   * cap waktu TEXT ISO  -> TIMESTAMPTZ; tanggal -> DATE
--   * REAL                -> DOUBLE PRECISION (REAL PostgreSQL hanya 4 bita;
--                            itu akan memicu revisi palsu pada pembandingan nilai)
--   * INTEGER 0/1         -> BOOLEAN
--   * AUTOINCREMENT       -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * payload_json TEXT   -> JSONB
--   * station mendapat kolom geom GEOMETRY(Point, 4326) dengan indeks GiST,
--     diturunkan otomatis dari lat/lng, untuk filter bbox (ST_Intersects).

CREATE TABLE IF NOT EXISTS station (
    uuid            TEXT PRIMARY KEY,
    kode            TEXT,
    initial         TEXT,
    name            TEXT,
    type            TEXT,              -- 'Reference' atau 'Sensor'
    lat             DOUBLE PRECISION,
    lng             DOUBLE PRECISION,
    kecamatan       TEXT,              -- tidak selalu benar; lihat catatan mutu
    kota            TEXT,
    alamat          TEXT,
    dioperasikan    TEXT,
    first_seen_utc  TIMESTAMPTZ NOT NULL,
    last_seen_utc   TIMESTAMPTZ NOT NULL,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    geom            geometry(Point, 4326) GENERATED ALWAYS AS (
                        CASE WHEN lat IS NOT NULL AND lng IS NOT NULL
                             THEN ST_SetSRID(ST_MakePoint(lng, lat), 4326) END
                    ) STORED
);
CREATE INDEX IF NOT EXISTS ix_station_geom ON station USING GIST (geom);

CREATE TABLE IF NOT EXISTS station_metric (
    station_uuid    TEXT NOT NULL REFERENCES station(uuid),
    metric          TEXT NOT NULL,
    unit_assumed    TEXT,
    first_seen_utc  TIMESTAMPTZ NOT NULL,
    last_seen_utc   TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (station_uuid, metric)
);

-- Konsentrasi mentah. Inti dataset.
CREATE TABLE IF NOT EXISTS observation (
    station_uuid    TEXT NOT NULL,
    metric          TEXT NOT NULL,
    ts_utc          TIMESTAMPTZ NOT NULL,
    value           DOUBLE PRECISION,
    qc              TEXT NOT NULL DEFAULT '',
    first_seen_utc  TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (station_uuid, metric, ts_utc)
);
CREATE INDEX IF NOT EXISTS ix_obs_ts      ON observation (ts_utc);
CREATE INDEX IF NOT EXISTS ix_obs_metric  ON observation (metric, ts_utc);

-- Jejak perubahan nilai pada koordinat yang sudah pernah tersimpan.
CREATE TABLE IF NOT EXISTS observation_revision (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series          TEXT NOT NULL DEFAULT 'observation',  -- 'observation' | 'observation_ispu'
    station_uuid    TEXT NOT NULL,
    metric          TEXT NOT NULL,
    ts_utc          TIMESTAMPTZ NOT NULL,
    old_value       DOUBLE PRECISION,
    new_value       DOUBLE PRECISION,
    noticed_utc     TIMESTAMPTZ NOT NULL
);

-- Nilai indeks per jam sebagaimana diterbitkan portal. Disimpan apa adanya,
-- tidak pernah diturunkan sendiri dari konsentrasi.
CREATE TABLE IF NOT EXISTS observation_ispu (
    station_uuid    TEXT NOT NULL,
    metric          TEXT NOT NULL,
    ts_utc          TIMESTAMPTZ NOT NULL,
    ispu            DOUBLE PRECISION,
    first_seen_utc  TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (station_uuid, metric, ts_utc)
);

CREATE TABLE IF NOT EXISTS meteo (
    station_uuid    TEXT NOT NULL,
    ts_utc          TIMESTAMPTZ NOT NULL,
    temp_c          DOUBLE PRECISION,
    rh_pct          DOUBLE PRECISION,
    wind_ms         DOUBLE PRECISION,
    qc              TEXT NOT NULL DEFAULT '',
    first_seen_utc  TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (station_uuid, ts_utc)
);

-- Agregat harian dari portal. concentration = maksimum konsentrasi 30 menit
-- parameter dominan pada hari UTC tersebut. Baris hari berjalan bersifat
-- sementara dan wajib ditimpa pada pengambilan berikutnya.
CREATE TABLE IF NOT EXISTS daily_ispu (
    station_uuid    TEXT NOT NULL,
    date_utc        DATE NOT NULL,
    max_ispu        INTEGER,
    concentration   DOUBLE PRECISION,
    dominant_metric TEXT,
    provisional     BOOLEAN NOT NULL DEFAULT FALSE,
    updated_utc     TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (station_uuid, date_utc)
);

-- Keadaan stasiun pada setiap lintasan. Dipakai untuk pemantauan kebasian.
CREATE TABLE IF NOT EXISTS station_status (
    station_uuid      TEXT NOT NULL,
    fetched_utc       TIMESTAMPTZ NOT NULL,
    ispu_value        INTEGER,
    ispu_category     TEXT,
    ispu_parameter    TEXT,
    ispu_concentration DOUBLE PRECISION,
    last_update_raw   TEXT,             -- teks mentah portal; formatnya tidak konsisten
    newest_raw_utc    TIMESTAMPTZ,
    cadence_minutes   INTEGER,
    n_observations    INTEGER,
    PRIMARY KEY (station_uuid, fetched_utc)
);

-- Satu baris per permintaan HTTP. Bukti provenans dan bahan audit.
CREATE TABLE IF NOT EXISTS fetch_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          TEXT NOT NULL,
    url             TEXT NOT NULL,
    fetched_utc     TIMESTAMPTZ NOT NULL,
    http_status     INTEGER,
    bytes           INTEGER,
    sha256          TEXT,
    elapsed_ms      INTEGER,
    parse_ok        BOOLEAN NOT NULL DEFAULT FALSE,
    n_rows          INTEGER DEFAULT 0,
    archive_path    TEXT,
    error           TEXT
);
CREATE INDEX IF NOT EXISTS ix_fetch_run ON fetch_log (run_id);

-- Satu baris per lintasan. Status 'aborted' berarti tidak ada yang ditulis.
CREATE TABLE IF NOT EXISTS run (
    run_id          TEXT PRIMARY KEY,
    kind            TEXT NOT NULL,     -- 'full' atau 'snapshot'
    started_utc     TIMESTAMPTZ NOT NULL,
    finished_utc    TIMESTAMPTZ,
    status          TEXT NOT NULL,     -- 'running' | 'ok' | 'partial' | 'aborted' | 'failed'
    stations_seen   INTEGER DEFAULT 0,
    stations_ok     INTEGER DEFAULT 0,
    rows_new        INTEGER DEFAULT 0,
    rows_revised    INTEGER DEFAULT 0,
    note            TEXT
);

-- Perubahan daftar stasiun: stasiun baru muncul atau berhenti terdaftar.
CREATE TABLE IF NOT EXISTS roster_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_uuid    TEXT NOT NULL,
    label           TEXT,
    event           TEXT NOT NULL,     -- 'appeared' | 'disappeared'
    at_utc          TIMESTAMPTZ NOT NULL
);

-- Cuplikan beranda: murah, dan menjadi pendeteksi gangguan portal.
CREATE TABLE IF NOT EXISTS snapshot (
    fetched_utc     TIMESTAMPTZ PRIMARY KEY,   -- waktu permintaan, bukan waktu penulisan
    update_time_wib TEXT,
    n_stations      INTEGER,
    payload_json    JSONB
);
